### ISSUE TITLE
Put uchiwa behind an Apache proxy

### ISSUE THREAD

**Issue by larsks** [centos-opstools/opstools-ansible#53]
Ideally, we could host both uchiwa and kibana on the same host on port 80, with one at `/kibana` and one `/uchiwa`.  This would also simplify our SSL configuration (since it would just be "configure ssl for apache" in both cases).

**Comment by paramite** [comment]
We could put Uchiwa behind proxy with /uchiwa prefix pretty easily I guess, but please note that with Kibana it is complety different topic. I've tried doing that for Kibana support PR, but Kibana has hardcoded prefix which has to be used, otherwise the UI either is not accessible at all or is failing.

**Comment by paramite** [comment]
This has been fixed by #66
